name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Syntax check (compileall)
        run: |
          python -m compileall -q src

      - name: Import smoke test
        run: |
          python - <<'PY'
          import sys
          sys.path.append('src')
          import corrected_mirrored_positioning  # noqa: F401
          import comprehensive_mirrored_test      # noqa: F401
          import create_mirrored_positioning_visualizations  # noqa: F401
          import create_showcase_visualizations   # noqa: F401
          print('Imports OK')
          PY
